### PR TITLE
83 add linting to GitHub test automation

### PR DESCRIPTION
**Pull request by tylers-username**
Closes https://github.com/platformsh/demo-project/issues/83 | Closes https://github.com/platformsh/demo-project/issues/85

### Summarized Changes

* .github/workflows/test.yaml - Add new lint/prettier commands to github MR tests
* backend/app/**/*.py - Python files were updated to meet to linting and prettier requirements
* backend/requirements.txt - Adds pylint and black for linting/prettier
* backend/scripts/lint_backend.sh & backend/scripts/prettier_backend.sh - Adds scripts for use with github workflow
* frontend/* - Files updated to meet linting and prettier requirements
* package.json(s) - each updated to include linting/prettier packages and tests

### CODE REVIEW

**Comment by tylers-username** [comment]
@chadwcarlson - I'm going to pause on this one to reduce noise to the commit log. Feel free to update the code if you know what the issue is.

Locally, the new linting and prettier commands work as expected. 

While running, the GitHub checks are (1) failing to use the Python packages installed by `npm install` and (2) they keep aborting with "This check was canceled".

**Comment by chadwcarlson** [comment]
@tylers-username Based on [the error](https://github.com/platformsh/demo-project/actions/runs/6750546723/job/18353154607#step:6:18), I would guess we need to add `black` to the [global installs ](https://github.com/platformsh/demo-project/blob/83-add-linting-to-github-test-automation/.github/workflows/test.yaml#L48)

**Comment by tylers-username** [comment]
@chadwcarlson - I was going to sneak some corrections into the `Upsun DEMO CI/demo-runthrough` test, but I don't have permission to manage the project that is being created.

I think the biggest step is implementing a 28 character limit on branch names and project titles for Upsun within these tests.

**Comment by tylers-username** [comment]
> @chadwcarlson - I was going to sneak some corrections into the `Upsun DEMO CI/demo-runthrough` test, but I don't have permission to manage the project that is being created.
> 
> I think the biggest step is implementing a 28 character limit on branch names and project titles for Upsun within these tests.

@chadwcarlson I restored `.github/workflows/project.yaml` to the state that we currently have in the `main` branch. This MR is ready for review.

**Pull request closed without merging**
